### ISSUE TITLE
There's a retain loop between SubscriptionListener and ListenerToken if listener is added by SubscriptionSession.add(_:ListenerType)

### ISSUE THREAD

**Issue by AirBlack** [pubnub/swift#92] opened 2021-12-27 11:36 UTC
![image](https://user-images.githubusercontent.com/5171605/147467488-5f24df9d-c54d-49d8-9522-3c0b58a691ad.png)
![Screenshot 2021-12-27 at 17 30 28](https://user-images.githubusercontent.com/5171605/147468105-b4fa93d9-e644-4a8f-9ac7-6555efd1da17.png)

SubscriptionListener has a strong reference to SubscriptionToken, SubscriptionToken has a strong reference to SubscriptionListener through it's cancellation closure capture group.

**Comment by dterekhov** [comment] 2022-12-11 22:01
It crashed for me at the same line: `self?.privateListeners.remove(listener)`
Here is a hint of how it was precisely caught: before the app was in the state `sceneWillResignActive` and on switching to `sceneDidBecomeActive` it crashed.

<img width="1094" alt="Screenshot 2022-12-12 at 12 56 16 AM" src="https://user-images.githubusercontent.com/9823122/206931267-04f7e723-8562-4344-bd62-ad3b52b435a5.png">

**Comment by AirBlack** [comment] 2022-12-16 16:37
It didn't crash for me but cos of retain loop and caching the subscription didn't clean itself and was stuck providing the app with duplicate/invalid values. I fixed it by somehow cleaning the subscription manually. I will post a workaround when I'll be next time around my working device.

**Comment by parfeon** [comment] 2022-12-21 10:28
All created listeners should call `cancel`, when there is no need in them.
```swift
listener = SubscriptionListener(queue: .main)
// configure listener with required handlers
pubnub.add(listener)
// we need to log out user or destroy PubNub instance
listener.cancel()
```

Right now Swift SDK creates sharable subscription session (to be used by multiple PubNub instances with same configuration), for which listeners are registered. `deinit` for `ListenerType` won't be called, because instance will exist.

**Comment by parfeon** [comment] 2022-12-22 12:11
There will be fix for this, so as soon as `subscription` listener instance will go out of scope, it will be removed from list of listeners and free-up resources properly.

**Closed** 2023-01-04 07:17 UTC
Labels: status: accepted

**Comment by luisescamilla13** [comment] 2023-02-14 21:54
Still getting the error with 6.0.3 :(

**Comment by parfeon** [comment] 2023-02-15 05:43
@luisescamilla13 hello. What exactly error do you get? 
This issue was about retain cycle.

**Comment by parfeon** [comment] 2023-02-15 07:04
@luisescamilla13 is it possible to show place. where you experience issue in same way, as shown in first message?

**Comment by luisescamilla13** [comment] 2023-02-15 17:21
@parfeon sure
This is the crash:
```
SIGSEGV : Crash due to signal: SIGSEGV(SEGV_MAPERR) at 00000010
$specialized Set._Variant.update(with:) (<compiler-generated>:0 )
```
This is the code where I initialize pubnub:
```
        // Setup PNConfiguration
        var configuration = PubNubConfiguration(publishKey: keys.publishKey, subscribeKey: keys.subscriptionKey, uuid: email)
        configuration.authKey = keys.token
        pubnub =  PubNub(configuration: configuration)
        listener = SubscriptionListener(queue: .main)
        pubnub.add(listener)
```
And here is the stack trace:
![Screen Shot 2023-02-15 at 11 19 20](https://user-images.githubusercontent.com/11380556/219105127-fe80ceda-05b6-42c5-bf0e-559f90ff18bd.png)

**Comment by parfeon** [comment] 2023-02-15 17:25
@luisescamilla13 do you store somewhere reference on `listener`? Without reference to it, the object will be deallocated right away.

**Comment by luisescamilla13** [comment] 2023-02-15 17:36
@parfeon yes sir, mi class has the following variable
`let listener: SubscriptionListener`
And the value is initialized in the init of my class

**Comment by parfeon** [comment] 2023-02-15 17:39
@luisescamilla13 is there any chance to have some minimum app which is able to reproduce this issue? With memory leak, we were able to reproduce it and fix, but I can't reproduce this one.

**Comment by luisescamilla13** [comment] 2023-02-15 17:44
@parfeon to be honest I haven't been able to reproduce it by myself, we just get this random crash every two or three weeks from different users. I'll let you know if I get more details. Thanks for the response.

**Comment by parfeon** [comment] 2023-02-15 17:55
@luisescamilla13 thank you!
If possible, can you create a new issue, so we won't bother issue author on a non-related topic?

**Comment by dterekhov** [comment] 2023-05-30 16:13
Continue getting crashes with the `6.0.5` latest version.
Please pay attention that the app crashes on `com.apple.root.user-initiated-qos.cooperative` thread + when going to the background state.

<img width="1005" alt="Screenshot 2023-05-30 at 7 07 04 PM" src="https://github.com/pubnub/swift/assets/9823122/e7872491-efea-4717-95af-cbde97052052">
<img width="1002" alt="Screenshot 2023-05-30 at 7 07 37 PM" src="https://github.com/pubnub/swift/assets/9823122/aca1aa3a-e694-48df-9804-d6abaf74f3bf">

cc @parfeon
Can you please re-open this issue?
